"""
Report Generator Tool — Execution Layer.

Stage 7: Report Generation.

Compiles all tool results, LLM insights, and metric summaries into:
  - A structured Markdown report  (output/reports/analysis_report.md)
  - A raw JSON dump               (output/reports/final_report.json)

The Markdown report is human-readable and suitable for conversion to PDF
via pandoc or any Markdown renderer.
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

from src.tools.base import BaseTool


class GenerateReportTool(BaseTool):
    """
    Compile all analysis results into a structured Markdown report.

    Inputs come from the MemorySystem via the `tool_results_json` parameter
    (a JSON string of the serialised tool results list) and the `llm_insights`
    parameter (the LLM's final interpretation dict).
    """

    name = "generate_report"
    description = (
        "Assemble the final analysis report from all tool results and LLM insights. "
        "Produces a Markdown report and a JSON data file. "
        "Returns output file paths."
    )

    def execute(
        self,
        dataset_name: str = "dataset",
        tool_results_json: str = "[]",
        llm_insights: dict[str, Any] | None = None,
        output_dir: str = "output/reports",
        **_: Any,
    ) -> dict[str, Any]:
        if llm_insights is None:
            llm_insights = {}
        # LLM sometimes double-serializes llm_insights as a JSON string
        if isinstance(llm_insights, str):
            try:
                llm_insights = json.loads(llm_insights)
            except json.JSONDecodeError:
                llm_insights = {}
        if not isinstance(llm_insights, dict):
            llm_insights = {}

        Path(output_dir).mkdir(parents=True, exist_ok=True)
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")

        if not tool_results_json or not tool_results_json.strip():
            tool_results_json = "[]"
        try:
            _parsed = json.loads(tool_results_json)
        except json.JSONDecodeError:
            try:
                _parsed, _offset = json.JSONDecoder().raw_decode(tool_results_json.strip())
            except json.JSONDecodeError:
                _parsed = []
        tool_results: list[dict[str, Any]] = _parsed if isinstance(_parsed, list) else []

        # Build Markdown
        md_lines: list[str] = [
            "# Agentic Data Analysis Report",
            "",
            f"**Dataset**: {dataset_name}  ",
            f"**Generated**: {timestamp}  ",
            "**Powered by**: Recursive Language Model Inference (Zhang et al., 2024)",
            "",
            "---",
            "",
        ]

        # Executive summary from LLM
        reasoning = llm_insights.get("reasoning", "")
        if reasoning:
            md_lines += ["## Executive Summary", "", reasoning, ""]

        insights = llm_insights.get("insights") or []
        recs = llm_insights.get("recommendations") or []

        if insights:
            md_lines += ["## Key Insights", ""]
            for i, insight in enumerate(insights, 1):
                md_lines.append(f"{i}. {insight}")
            md_lines.append("")

        # Recommendations
        if recs:
            md_lines += ["## Recommendations", ""]
            for rec in recs:
                md_lines.append(f"- {rec}")
            md_lines.append("")

        # Model performance
        best_model = llm_insights.get("best_model")
        key_metrics = llm_insights.get("key_metrics", {})
        if best_model or key_metrics:
            md_lines += ["## Model Performance", ""]
            if best_model:
                md_lines.append(f"**Best model**: {best_model}")
            if key_metrics:
                md_lines.append("")
                md_lines.append("| Metric | Value |")
                md_lines.append("|--------|-------|")
                for k, v in key_metrics.items():
                    md_lines.append(f"| {k} | {v} |")
            md_lines.append("")

        # Tool execution log
        if tool_results:
            md_lines += ["## Tool Execution Log", "", "| Tool | Status | Summary |", "|------|--------|---------|"]
            for r in tool_results:
                name = r.get("tool_name", "?")
                status = r.get("status", "?")
                summary = r.get("output", {}).get("summary", r.get("error", ""))[:120]
                md_lines.append(f"| {name} | {status} | {summary} |")
            md_lines.append("")

        md_lines += [
            "---",
            "",
            "*Report generated by the Agentic Data Analysis System.*",
            "*Architecture: Reasoning ↔ Execution separation with RLM context offloading.*",
        ]

        md_content = "\n".join(md_lines)
        md_path = Path(output_dir) / f"{dataset_name}_report.md"
        md_path.write_text(md_content, encoding="utf-8")

        json_path = Path(output_dir) / f"{dataset_name}_raw.json"
        json_path.write_text(
            json.dumps(
                {
                    "timestamp": timestamp,
                    "dataset": dataset_name,
                    "llm_insights": llm_insights,
                    "tool_results": tool_results,
                },
                indent=2,
                default=str,
            ),
            encoding="utf-8",
        )

        return {
            "summary": f"Report generated: {md_path} and {json_path}.",
            "markdown_path": str(md_path),
            "json_path": str(json_path),
            "n_insights": len(insights),
            "n_recommendations": len(recs),
        }

    def get_schema(self) -> dict[str, Any]:
        return {
            "dataset_name": {
                "type": "string",
                "description": "Name used in the report filename and header.",
                "required": False,
            },
            "tool_results_json": {
                "type": "string",
                "description": "JSON-serialised list of tool result dicts.",
                "required": False,
            },
            "llm_insights": {
                "type": "dict",
                "description": "Final LLM interpretation dict (insights, recommendations, metrics).",
                "required": False,
            },
            "output_dir": {
                "type": "string",
                "description": "Output directory. Default: output/reports.",
                "required": False,
            },
        }
